name: CI
on:
  workflow_dispatch:
  push:

permissions:
  actions: write
  checks: write
  contents: write

# Cancel in-progress runs in current workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdk-generate:
    name: Generate SDKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
        shell: bash
      - run: |
          wget https://github.com/go-swagger/go-swagger/releases/latest/download/swagger_linux_amd64 -O "$GOPATH/bin/swagger"
          chmod +x "$GOPATH/bin/swagger"
          bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b $GOPATH/bin ory
        shell: bash
      - run: make sdk
      - run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update"
            git push
          fi
